---
abstract: 'Perl extension for NLP of the Portuguese'
author:
  - 'Alberto Simoes <ambs@di.uminho.pt>'
build_requires:
  File::Slurp: '0'
  File::Temp: '0'
  Lingua::PT::Abbrev: '0.05'
  Test::Pod: '1.00'
  Test::Pod::Coverage: '0.08'
configure_requires:
  ExtUtils::MakeMaker: '6.55'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-PT-PLNbase
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::PT::Abbrev: '0.05'
version: '0.26'
