--- #YAML:1.0
name:               Lingua-PT-PLNbase
version:            0.23
abstract:           Perl extension for NLP of the Portuguese
author:
    - Alberto Simoes <ambs@di.uminho.pt>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.55
build_requires:
    File::Slurp:          0
    File::Temp:           0
    Test::Pod:            1.00
    Test::Pod::Coverage:  0.08
requires:
    Lingua::PT::Abbrev:  0.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
