--- #YAML:1.0
name:               Lingua-PT-PLNbase
version:            0.21
abstract:           Perl extension for NLP of the Portuguese
author:
    - Alberto Simoes <ambs@di.uminho.pt>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lingua::PT::Abbrev:   0.05
    Test::Pod:            1
    Test::Pod::Coverage:  0.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
